name: tawseel
description: NGT company app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^0.22.0
  gap: ^2.0.0
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  jiffy: ^5.0.0
  lottie: ^1.0.0
  liquid_pull_to_refresh: ^3.0.1
  simple_animations: ^3.0.0+2
  cached_network_image: ^3.0.0
  package_info_plus: ^3.0.2
  internet_connection_checker: ^0.0.1+4
  screenshot: ^1.2.3
  permission_handler: ^10.0.0
  image_gallery_saver: '^1.7.1'
  qr_code_scanner: ^1.0.1
  local_auth: ^2.1.2
  url_launcher: ^6.1.6
  restart_app: ^1.1.0+1
  animated_bottom_navigation_bar: ^1.1.0+1
  custom_navigation_bar: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/cat/
    - assets/fonts/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
